export const componentsList = [
  'attach',
  'badge',
  'button',
  'buttonGroup',
  'checkbox',
  'divider',
  // "dropdown", // У дропдауна нет никаких токенов
  'header',
  'icon',
  'image',
  'layerManager',
  'link',
  'listTile',
  'menu',
  'messageBox',
  'modal',
  'popup',
  'progress',
  'radioButton',
  'radiobox',
  'select',
  'showcase',
  'slider',
  'spacer',
  'spin',
  'tabsMenu',
  'tabsPanes',
  'text',
  'textarea',
  'textinput',
  'theme',
  'tooltip',
  'tumbler',
  'userPic',
]

// List of components that should not be shown
export const excludeComponentsList = ['calendar']
